name: CI

on:
  push:
    branches:
      - stable

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: checkout stable branch
      uses: actions/checkout@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: projectcaluma/caluma-demo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: caluma-demo/Dockerfile
